# Generated by Django 2.2.5 on 2020-02-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_displaysr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
