# Generated by Django 2.2.5 on 2020-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_displaymo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
