# Generated by Django 2.2.5 on 2020-03-10 15:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_detail_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('ticker', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
