# Generated by Django 2.2.5 on 2020-03-17 10:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_stockreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCorrelation',
            fields=[
                ('ticker', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('dataset', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ticker_index', models.CharField(max_length=6)),
                ('dataset_index', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('slope', models.FloatField(blank=True, default=None, null=True)),
                ('intercept', models.FloatField(blank=True, default=None, null=True)),
                ('stderr', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
